### ISSUE TITLE
Модуль несовместим с сайтами в кодировке, отличной от UTF-8

### ISSUE THREAD

**Issue by freeriderND** [rbkmoney/rbkmoney-cms-bitrix#8]
![default](https://user-images.githubusercontent.com/19728752/41967741-c260c63c-7a1b-11e8-93e0-673d393ee090.png)
![2](https://user-images.githubusercontent.com/19728752/41967742-c2876526-7a1b-11e8-859d-7a3e230a165d.png)
![3](https://user-images.githubusercontent.com/19728752/41967744-c2aedb6a-7a1b-11e8-95ef-5e49b4cb83dc.png)

**Comment by avcherkasov** [comment]
Если у вас возникают проблемы с кодировкой, то вы можете перевести файлы модуля в необходимую вам кодировку [вручную](https://github.com/rbkmoney/rbkmoney-cms-bitrix#%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D1%8B-%D1%81-%D0%BA%D0%BE%D0%B4%D0%B8%D1%80%D0%BE%D0%B2%D0%BA%D0%BE%D0%B9-%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2). Об этом написано в документации.
